#!/usr/bin/env bash
#Indefinitly runs Script and gives other time to clean up.

trap "echo I am invincible!!!" SIGTERM
x=1
while [ "$x" -gt 0 ]
do
	echo "To infinity and beyond"
	x=$((x+1))
	sleep 2
done
